
### get user number 4
GET http://localhost:8080/api/v1/user/4
Accept: application/json

### add salary to user number 4
POST http://localhost:8080/api/v1/salary
Content-Type: application/json

{
  "userId": 1002,
  "salary": 1852.3,
  "employer": "Google",
  "startDate": "2019-01-01",
  "description": "Software Engineer"
}

### get user number 4
GET http://localhost:8080/api/v1/user/4
Accept: application/json


### get user salary
GET http://localhost:8080/api/v1/salary/user/4
Accept: application/json