### get all users
GET http://localhost:8080/api/v1/user
Accept: application/json


### get user by id
GET http://localhost:8080/api/v1/user/10
Accept: application/json


### get user by email
GET http://localhost:8080/api/v1/user/email/dnetleyp@dell.com
Accept: application/json

### create user
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "firstName": "חגי",
  "lastName": "אלבז",
  "email": "hagayelbaz@gmail.com",
  "phoneNumber": "053-9525639"
}

### get user by email
GET http://localhost:8080/api/v1/user/email/hagayelbaz@gmail.com
Accept: application/json