# Please check the doc before running the application

server:
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MortgageIL
    username: postgres
    password: gba581p
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 0


api:
  external:
    data-gov:
      base-url: https://data.gov.il/api/3/action/datastore_search
      average-index-linked: 96ba107d-cc15-41cf-b223-5bb592e14666
    boi:
      format:
        json: sdmx-json
        csv: series-csv
        xml: sdmx-ml
      url:
        base-url: https://edge.boi.gov.il/FusionEdgeServer/sdmx/v2/data/dataflow
        boi-interest: BOI.STATISTICS/BR/1.0/MNT_RIB_BOI_D.D.RIB_BOI
        boi-current-interest: https://boi.org.il/PublicApi/GetInterest
        cpi: BOI.STATISTICS/PRI/1.0/BI_CPI_NO_ADMN_M.CPI.CPI_2_29_1.MAIN.M.N._Z._Z.I_JAN20_L._Z.A._Z._Z._Z
        cpi-percentage: BOI.STATISTICS/PRI/1.0/CP_PCH.CPI.CPI_2_29.MAIN.M.N._Z._Z.PT._Z.A.G1._Z.CP
        cpi-change-in-last-12-months: BOI.STATISTICS/PRI/1.0/CP_PCHYTY.CPI.CPI_2_29.MAIN.M.N._Z._Z.PT._Z.A.G12._Z.CP
      params:
        lastOne: lastNObservations
