server:
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MortgageIL
    username: postgres
    password: gba581p
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


api:
  external:
    data-gov:
      base-url: https://data.gov.il/api/3/action/datastore_search
      average-index-linked: 96ba107d-cc15-41cf-b223-5bb592e14666